CONFIRMATION_PHRASES = [
    "yes",
    "yes please",
    "yes sure",
    "yeah",
    "I do",
    "yup",
    "exactly",
    "absolutely",
    "confirm",
    "certainly",
    "affirmative",
    "indeed",
    "you got it",
    "affirmative, captain",
    "by all means",
    "definitely",
    "for sure",
    "without a doubt",
    "of course",
    "sure thing",
    "roger that",
    "OK",
    "okay",
    "got it",
    "gotcha",
    "sounds good",
    "sounds great",
    "go ahead",
    "please do",
    "please proceed",
    "go for it",
    "do it",
    "execute",
    "proceed",
    "go on",
    "continue",
    "right",
    "that's right",
    "that's correct",
    "you're right",
    "indeed",
    "absolutely right",
    "correct",
    "precisely",
    "definitely yes",
    "positive",
    "confirmed",
    "agreed",
    "all right",
    "aye aye",
    "fine",
    "surely",
    "why not",
    "yeah why not",
    "yeah go ahead",
    "for sure go ahead",
    "absolutely go ahead",
    "sure that's fine",
    "sure that works",
    "sure sounds good",
    "sure why not",
    "sure do it",
    "sure proceed",
    "sure go on",
    "sure continue",
    "sure you can",
    "sure you may",
    "please proceed captain",
    "please do it captain",
    "go ahead captain",
    "execute captain",
    "affirmative sir",
    "yes sir",
    "right away sir",
    "very well sir",
    "of course sir",
    "as you wish",
    "whatever you say",
    "whatever you want",
    "it's a go",
    "permission granted",
    "got it chief",
    "understood",
    "acknowledged",
    "roger roger",
    "received and understood",
    "message received",
    "10-4",
    "loud and clear",
    "right on",
    "no problem",
    "I'm on it",
    "I'll do it",
    "I'll get right on it",
    "I'll handle it",
    "I'll take care of it",
    "I'm here to help",
    "consider it done",
    "count me in",
    "that's a plan",
    "you bet",
    "sounds like a plan",
    "go for it boss",
    "sure thing boss",
    "absolutely boss",
    "as you command",
    "as you wish boss",
    "I'm at your service",
    "anything you say",
    "with pleasure",
    "for you anything",
]

WAKE_UP_PHRASES = [
    "Hello Jarvis",
    "Wake up",
    "Action",
    "Shine",
    "Hey",
    "Hello",
    "Jarvis",
    "Hey Jarvis",
    "Activate",
    "Jarvis",
    "action",
    "Wake up Jarvis",
    "Hey AI Jarvis",
    "Jarvis listen up",
    "Jarvis I need you",
    "Jarvis wake up",
    "Jarvis are you there?",
    "Okay Jarvis let's talk",
    "Good morning Jarvis",
    "Hey there Jarvis",
    "Jarvis time to work",
    "Hey buddy Jarvis",
    "Jarvis it's showtime",
    "Computer activate Jarvis",
    "Hello my virtual assistant Jarvis",
    "Jarvis at your service",
    "Jarvis wakey-wakey",
    "Hey Jarvis time to shine",
    "Rise and shine Jarvis",
    "Jarvis open up",
    "Hey Jarvis ready for action",
]


COMMAND_PHRASES = {
    "open browser": ["internet", "web", "browser", "firefox", "open browser", "start browser", "launch browser", "open firefox", "open web", "open internet"],
    "enter the matrix": ["matrix", "the matrix","terminal", "open terminal", "the terminal"],
    "exit the matrix": ["return to zion", "zion", "return", "go back", "back"],
    "execute order 66": ["66", "order 66", "execute 66", "execute order"],
    "open visual studio code": ["open visual studio", "start visual studio", "launch visual studio", "let's code", "code", "visual studio", "visual studio code", "launch code editor", "code editor", "ooen code editor"],
    "get date": ["get date", "show date", "what's the date", "what day is it?", "what day", "date" ,"day"],
    "get time": ["get time", "show time", "what's the time", "what time is it?", "what time", "time"],
    "open discord": ["open discord", "start discord", "run discord"],
    "google this": ["search", "google", "search google", "find"]
}
